// ─── Universities ────────────────────────────────────────────────────────────
export const universities12 = [
  {
    id: "dtu",
    abbr: "DTU",
    name: "Delhi Technological University",
    fullName: "Delhi Technological University",
    location: "Rohini, New Delhi",
    established: 1941,
    type: "Public",
    affiliation: "State University",
    color: "#7c3aed",
    reviews: 1820,
    professors: 210,
    rating: 4.3,
    departments: [
      "Computer Science",
      "Electronics & Communication",
      "Mechanical",
      "Civil",
      "Electrical",
      "Mathematics",
      "Physics",
      "Chemistry",
    ],
    description:
      "DTU is one of the oldest and most prestigious technical universities in India, known for its engineering excellence and strong industry connections.",
    website: "https://dtu.ac.in",
    phone: "+91-11-27871018",
    email: "info@dtu.ac.in",
    naacGrade: "A+",
    nirfRank: 36,
    image: null,
  },
  {
    id: "nsut",
    abbr: "NSUT",
    name: "Netaji Subhas University of Technology",
    fullName: "Netaji Subhas University of Technology",
    location: "Dwarka, New Delhi",
    established: 1983,
    type: "Public",
    affiliation: "State University",
    color: "#3b82f6",
    reviews: 1240,
    professors: 160,
    rating: 4.1,
    departments: [
      "Computer Science",
      "Information Technology",
      "Electronics",
      "Mechanical",
      "Instrumentation",
      "Bio-Technology",
    ],
    description:
      "NSUT (formerly NSIT) is a premier technical institution in Delhi, celebrated for its rigorous academics and active student culture.",
    website: "https://nsut.ac.in",
    phone: "+91-11-25099054",
    email: "info@nsut.ac.in",
    naacGrade: "A",
    nirfRank: 58,
    image: null,
  },
  {
    id: "iitd",
    abbr: "IIT-D",
    name: "IIT Delhi",
    fullName: "Indian Institute of Technology Delhi",
    location: "Hauz Khas, New Delhi",
    established: 1961,
    type: "Public (Institute of National Importance)",
    affiliation: "Central University",
    color: "#06b6d4",
    reviews: 2560,
    professors: 580,
    rating: 4.8,
    departments: [
      "Computer Science",
      "Electrical Engineering",
      "Mechanical",
      "Chemical",
      "Physics",
      "Mathematics",
      "Management Studies",
      "Humanities",
    ],
    description:
      "IIT Delhi is one of India's most prestigious institutions, consistently ranked among the top engineering colleges globally for research and academics.",
    website: "https://iitd.ac.in",
    phone: "+91-11-26591999",
    email: "webmaster@admin.iitd.ac.in",
    naacGrade: "A++",
    nirfRank: 2,
    image: null,
  },
  {
    id: "vit",
    abbr: "VIT",
    name: "VIT Vellore",
    fullName: "Vellore Institute of Technology",
    location: "Vellore, Tamil Nadu",
    established: 1984,
    type: "Private (Deemed)",
    affiliation: "Deemed University",
    color: "#8b5cf6",
    reviews: 920,
    professors: 2400,
    rating: 4.0,
    departments: [
      "Computer Science",
      "Information Technology",
      "Electronics",
      "Mechanical",
      "Civil",
      "Biotechnology",
      "MBA",
      "Law",
    ],
    description:
      "VIT Vellore is one of India's largest private universities, known for its modern campus, industry collaborations and global student community.",
    website: "https://vit.ac.in",
    phone: "+91-416-2202020",
    email: "ugadmission@vit.ac.in",
    naacGrade: "A++",
    nirfRank: 11,
    image: null,
  },
  {
    id: "srm",
    abbr: "SRM",
    name: "SRM Chennai",
    fullName: "SRM Institute of Science and Technology",
    location: "Kattankulathur, Chennai",
    established: 1985,
    type: "Private (Deemed)",
    affiliation: "Deemed University",
    color: "#10b981",
    reviews: 780,
    professors: 3000,
    rating: 3.9,
    departments: [
      "Computer Science",
      "Electronics",
      "Mechanical",
      "Civil",
      "Biomedical",
      "MBA",
      "Architecture",
    ],
    description:
      "SRM is a top-ranked private university with state-of-the-art facilities, strong research output and a vibrant campus life.",
    website: "https://srmist.edu.in",
    phone: "+91-44-27452270",
    email: "info@srmist.edu.in",
    naacGrade: "A++",
    nirfRank: 20,
    image: null,
  },
  {
    id: "amity",
    abbr: "AUL",
    name: "Amity University",
    fullName: "Amity University, Noida",
    location: "Noida, Uttar Pradesh",
    established: 2005,
    type: "Private",
    affiliation: "Private University",
    color: "#f59e0b",
    reviews: 650,
    professors: 1800,
    rating: 3.8,
    departments: [
      "Computer Science",
      "Law",
      "Management",
      "Journalism",
      "Architecture",
      "Fashion Design",
      "Biotechnology",
    ],
    description:
      "Amity is one of India's most recognized private universities, offering diverse programs across disciplines with an international outlook.",
    website: "https://amity.edu",
    phone: "+91-120-4392000",
    email: "admissions@amity.edu",
    naacGrade: "A+",
    nirfRank: 45,
    image: null,
  },
];

export const universities = [
  {
    _id: "65ce49b27da507abca871ec3",
    name: "Guru Gobind Singh Indraprastha University",
    programsOffered: [],
    date: "2024-02-15T17:28:18.000Z",
    __v: 1,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRk2HA1GepM9VuLEvMSZ9GvVi3ZZF_C1dQzow&s",
    abbreviation: "GGSIPU",
    description:
      "Guru Gobind Singh Indraprastha University (GGSIPU), located in Delhi, India, is a state university renowned for its focus on professional and technical education. Established in 1998, the university has rapidly grown to encompass a wide array of disciplines, with particular strength in engineering, technology, management, law, and medical sciences. GGSIPU is recognized for its emphasis on practical, industry-relevant curriculum and its commitment to fostering innovation and entrepreneurship. The university’s engineering programs, including computer science, information technology, and electronics and communication engineering, are highly regarded, attracting students from across the country. The law school at GGSIPU is also well-established, offering comprehensive legal education and contributing significantly to legal scholarship. Furthermore, the university has made substantial strides in medical education and healthcare through its affiliated medical colleges and hospitals. GGSIPU aims to provide quality education and contribute to the development of skilled professionals who can meet the challenges of a rapidly evolving global landscape. The university maintains a strong reputation for its rigorous academic standards, its focus on research, and its commitment to providing a holistic educational experience.",
    averageRating: 0,
    campusFacilities: [],
    country: "India",
    degreesOffered: [],
    departments: [],
    isActive: true,
    keywords: [],
    popularCourses: [],
    slug: "guru-gobind-singh-indraprastha-university",
    totalProfessors: 0,
    totalReviews: 0,
    updatedAt: "2026-06-19T03:34:11.849Z",
    accreditation: "NAAC",
    address: "Sector 16C, Dwarka, New Delhi, Delhi 110078",
    averagePackage: null,
    campusSize: null,
    city: "New Delhi",
    contactEmail: "pro@ipu.ac.in",
    contactPhone: "+91-11-25302170",
    establishedYear: 1998,
    facultyCount: null,
    highestPackage: null,
    metaDescription: null,
    metaTitle: "Guru Gobind Singh Indraprastha University",
    nirfRanking: null,
    placementRate: null,
    qsWorldRanking: null,
    state: "Delhi",
    universityType: "Public",
    website: "https://www.ipu.ac.in/",
  },
  {
    _id: "65ce541f7da507abca871f97",
    name: "University of Delhi",
    programsOffered: ["Undergraduate", "Postgraduate", "Doctoral"],
    date: "2024-02-15T18:12:47.000Z",
    __v: 2,
    image:
      "https://static.toiimg.com/thumb/msid-76213614,width-400,resizemode-4/76213614.jpg",
    abbreviation: "DU",
    description:
      "University of Delhi, located in Delhi, India, is a central university renowned for its academic excellence across a wide range of disciplines. Established in 1922, the university has grown into a leading institution of higher learning, attracting students from across India and internationally. It is particularly well-regarded for its programs in the humanities, social sciences, law, sciences, and commerce. Several colleges affiliated with the University of Delhi, such as St. Stephen's College, Hindu College, Miranda House, and Shri Ram College of Commerce (SRCC), consistently rank among the top academic institutions in India. The university's faculty comprises accomplished scholars and researchers, contributing significantly to their respective fields. The University of Delhi maintains a strong reputation for rigorous academics, a diverse student body, and a commitment to research and innovation. Its extensive network of alumni holds prominent positions in government, industry, academia, and the arts, reflecting the university's impactful contribution to society. The university continues to adapt and evolve, embracing new technologies and pedagogical approaches to meet the changing needs of its students and the global community.",
    averageRating: 0,
    campusFacilities: ["Library", "Hostel", "Canteen", "Sports Complex", "Gym"],
    country: "India",
    degreesOffered: [
      "BA",
      "BSc",
      "BCom",
      "LLB",
      "MBA",
      "MA",
      "MSc",
      "MCom",
      "LLM",
      "PhD",
    ],
    departments: ["Arts", "Commerce", "Science", "Law", "Management"],
    isActive: true,
    keywords: ["University of Delhi", "DU", "Delhi University"],
    popularCourses: [
      "BA Economics",
      "BCom Honours",
      "BSc Physics",
      "LLB",
      "MBA",
    ],
    slug: "university-of-delhi",
    totalProfessors: 0,
    totalReviews: 0,
    updatedAt: "2026-06-19T03:34:14.051Z",
    accreditation: "NAAC",
    address: "University of Delhi, Delhi-110007",
    averagePackage: 6.5,
    campusSize: "69 acres",
    city: "New Delhi",
    contactEmail: "du@du.ac.in",
    contactPhone: "+91-11-27667853",
    establishedYear: 1922,
    facultyCount: 302,
    highestPackage: 20,
    metaDescription:
      "The University of Delhi is a premier institution of higher learning in India.",
    metaTitle: "University of Delhi",
    nirfRanking: 11,
    placementRate: 80,
    qsWorldRanking: 521,
    state: "Delhi",
    universityType: "Public",
    website: "https://www.du.ac.in/",
  },
  {
    _id: "65ce5f997da507abca871feb",
    name: "Jawaharlal Nehru University",
    programsOffered: ["Undergraduate", "Postgraduate", "Doctoral"],
    date: "2024-02-15T19:01:45.000Z",
    __v: 2,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsy12XeVfpg5_47DgGnOJY2kqAltk7OQkGbw&s",
    abbreviation: "JNU",
    description:
      "Jawaharlal Nehru University (JNU), located in New Delhi, India, is a central public university renowned for its focus on social sciences, humanities, and international studies. Established in 1969, JNU has gained a reputation for academic excellence and critical thinking, fostering a vibrant intellectual environment. The university is particularly well-known for its strong programs in economics, political science, sociology, history, international relations, languages, and literature. JNU's academic strengths lie in its interdisciplinary approach, research-intensive environment, and emphasis on social justice. The university consistently ranks among the top universities in India and is recognized internationally for its contributions to research and scholarship in its core disciplines. JNU also houses specialized centres for the study of areas such as biotechnology, Sanskrit, and social medicine and community health. The university's commitment to inclusivity and diverse perspectives has contributed to its distinctive academic culture.",
    averageRating: 0,
    campusFacilities: [
      "Library",
      "Hostel",
      "Canteen",
      "Sports Complex",
      "Health Centre",
    ],
    country: "India",
    degreesOffered: ["BA", "MA", "MSc", "MPhil", "PhD"],
    departments: [
      "School of Social Sciences",
      "School of Language, Literature and Culture Studies",
      "School of International Studies",
      "School of Life Sciences",
      "School of Physical Sciences",
      "School of Environmental Sciences",
      "School of Computer and Systems Sciences",
    ],
    isActive: true,
    keywords: [
      "JNU",
      "Jawaharlal Nehru University",
      "Public University",
      "New Delhi",
    ],
    popularCourses: [
      "MA in Economics",
      "MSc in Biotechnology",
      "BA in English",
      "MA in International Relations",
      "PhD in Computer Science",
    ],
    slug: "jawaharlal-nehru-university",
    totalProfessors: 0,
    totalReviews: 0,
    updatedAt: "2026-06-19T03:34:16.338Z",
    accreditation: "NAAC",
    address: "Jawaharlal Nehru University, New Mehrauli Road, New Delhi 110067",
    averagePackage: 7.5,
    campusSize: "1000 acres",
    city: "New Delhi",
    contactEmail: "info@jnu.ac.in",
    contactPhone: "+91-11-26742605",
    establishedYear: 1969,
    facultyCount: 630,
    highestPackage: 20,
    metaDescription:
      "Jawaharlal Nehru University is a public university located in New Delhi, India.",
    metaTitle: "Jawaharlal Nehru University",
    nirfRanking: 2,
    placementRate: 80,
    qsWorldRanking: 561,
    state: "Delhi",
    universityType: "Public",
    website: "https://www.jnu.ac.in",
  },
];

// ─── Professors ───────────────────────────────────────────────────────────────
export const professors = [
  {
    id: "prof-1",
    name: "Dr. Rajesh Kumar",
    title: "Professor & HOD",
    dept: "Computer Science",
    universityId: "dtu",
    universityName: "DTU, Delhi",
    rating: 4.7,
    totalReviews: 312,
    avatar: "RK",
    avatarBg: "linear-gradient(135deg, #7c3aed, #3b82f6)",
    tags: ["Clear Explanations", "Helpful", "Research-focused", "Approachable"],
    courses: [
      "Data Structures & Algorithms",
      "Algorithm Design",
      "Theory of Computation",
      "Discrete Mathematics",
    ],
    wouldTakeAgain: 92,
    difficultyLevel: 3.4,
    bio: "Dr. Rajesh Kumar is a distinguished professor with over 18 years of teaching experience. He holds a PhD from IIT Bombay and has published 40+ papers in IEEE and ACM journals. His research focuses on distributed systems and machine learning.",
    email: "rajesh.kumar@dtu.ac.in",
    office: "Room 304, CS Block",
    officeHours: "Mon, Wed 2–4 PM",
    joined: 2006,
    ratingBreakdown: {
      clarity: 4.8,
      helpfulness: 4.6,
      knowledge: 4.9,
      fairness: 4.5,
    },
  },
  {
    id: "prof-2",
    name: "Prof. Priya Sharma",
    title: "Associate Professor",
    dept: "Electronics & Communication",
    universityId: "nsut",
    universityName: "NSUT, Delhi",
    rating: 4.5,
    totalReviews: 198,
    avatar: "PS",
    avatarBg: "linear-gradient(135deg, #06b6d4, #8b5cf6)",
    tags: ["Interactive", "Industry Connect", "Project-based", "Motivating"],
    courses: [
      "Digital Electronics",
      "VLSI Design",
      "Signals & Systems",
      "Microprocessors",
    ],
    wouldTakeAgain: 87,
    difficultyLevel: 3.8,
    bio: "Prof. Priya Sharma brings 12 years of academic and industry experience. Previously at Texas Instruments, she now leads research in VLSI and embedded systems at NSUT. She is known for her hands-on teaching approach.",
    email: "priya.sharma@nsut.ac.in",
    office: "ECE Block, 2nd Floor",
    officeHours: "Tue, Thu 11 AM–1 PM",
    joined: 2012,
    ratingBreakdown: {
      clarity: 4.6,
      helpfulness: 4.7,
      knowledge: 4.5,
      fairness: 4.3,
    },
  },
  {
    id: "prof-3",
    name: "Dr. Amit Singh",
    title: "Professor",
    dept: "Mathematics",
    universityId: "iitd",
    universityName: "IIT Delhi",
    rating: 4.9,
    totalReviews: 520,
    avatar: "AS",
    avatarBg: "linear-gradient(135deg, #f59e0b, #ef4444)",
    tags: ["Brilliant", "Rigorous", "Inspiring", "Nobel-level Thinking"],
    courses: [
      "Real Analysis",
      "Linear Algebra",
      "Differential Equations",
      "Probability Theory",
    ],
    wouldTakeAgain: 96,
    difficultyLevel: 4.8,
    bio: "Dr. Amit Singh is one of the most celebrated math professors in India. A gold medalist from IIT Kanpur and PhD from MIT, he has mentored over 30 PhD students. His lectures are legendary for their depth and clarity.",
    email: "amit.singh@iitd.ac.in",
    office: "Maths Department, Block VII",
    officeHours: "Fri 10 AM–12 PM",
    joined: 2003,
    ratingBreakdown: {
      clarity: 4.9,
      helpfulness: 4.8,
      knowledge: 5.0,
      fairness: 4.7,
    },
  },
  {
    id: "prof-4",
    name: "Dr. Meera Nair",
    title: "Assistant Professor",
    dept: "Computer Science",
    universityId: "vit",
    universityName: "VIT Vellore",
    rating: 4.2,
    totalReviews: 145,
    avatar: "MN",
    avatarBg: "linear-gradient(135deg, #10b981, #3b82f6)",
    tags: ["Friendly", "Updated Curriculum", "Practical Focus"],
    courses: [
      "Web Technologies",
      "Cloud Computing",
      "Database Systems",
      "Software Engineering",
    ],
    wouldTakeAgain: 78,
    difficultyLevel: 2.9,
    bio: "Dr. Meera Nair completed her PhD from NIT Trichy and specializes in cloud-native architectures and DevOps. She actively collaborates with startups and brings real-world case studies to the classroom.",
    email: "meera.nair@vit.ac.in",
    office: "SJT Block, 5th Floor",
    officeHours: "Mon–Fri 12–1 PM",
    joined: 2018,
    ratingBreakdown: {
      clarity: 4.2,
      helpfulness: 4.5,
      knowledge: 4.1,
      fairness: 4.0,
    },
  },
  {
    id: "prof-5",
    name: "Prof. Suresh Rao",
    title: "Senior Professor",
    dept: "Mechanical Engineering",
    universityId: "srm",
    universityName: "SRM Chennai",
    rating: 3.8,
    totalReviews: 88,
    avatar: "SR",
    avatarBg: "linear-gradient(135deg, #ef4444, #f59e0b)",
    tags: ["Experienced", "Theory-heavy", "Strict"],
    courses: [
      "Thermodynamics",
      "Fluid Mechanics",
      "Heat Transfer",
      "Machine Design",
    ],
    wouldTakeAgain: 61,
    difficultyLevel: 4.2,
    bio: "Prof. Suresh Rao has 25+ years of experience in mechanical engineering education. A traditionalist in teaching, he emphasizes fundamentals and has authored two textbooks used in universities across South India.",
    email: "suresh.rao@srmist.edu.in",
    office: "Mech Block C, Ground Floor",
    officeHours: "Wed 3–5 PM",
    joined: 1999,
    ratingBreakdown: {
      clarity: 3.5,
      helpfulness: 3.8,
      knowledge: 4.6,
      fairness: 3.4,
    },
  },
  {
    id: "prof-6",
    name: "Dr. Ananya Bose",
    title: "Associate Professor",
    dept: "Management Studies",
    universityId: "amity",
    universityName: "Amity University, Noida",
    rating: 4.4,
    totalReviews: 203,
    avatar: "AB",
    avatarBg: "linear-gradient(135deg, #8b5cf6, #06b6d4)",
    tags: [
      "Case Study Expert",
      "Industry Insights",
      "Engaging",
      "Open to Discussion",
    ],
    courses: [
      "Strategic Management",
      "Organizational Behavior",
      "Business Ethics",
      "Leadership",
    ],
    wouldTakeAgain: 85,
    difficultyLevel: 2.6,
    bio: "Dr. Ananya Bose holds an MBA from IIM Calcutta and PhD from Delhi University. With 14 years in academia and prior consulting experience at McKinsey, she bridges theory and business practice effectively.",
    email: "ananya.bose@amity.edu",
    office: "Management Block, Room 112",
    officeHours: "Tue, Thu 2–4 PM",
    joined: 2010,
    ratingBreakdown: {
      clarity: 4.5,
      helpfulness: 4.6,
      knowledge: 4.4,
      fairness: 4.2,
    },
  },
];

// ─── Reviews ──────────────────────────────────────────────────────────────────
export const reviews = [
  {
    id: "r1",
    professorId: "prof-1",
    author: "Arjun M.",
    year: "B.Tech 3rd Year, CSE",
    rating: 5,
    course: "Data Structures & Algorithms",
    date: "2024-11-15",
    text: "Hands down the best DSA professor at DTU. His explanations are crystal clear and he genuinely cares about students understanding the material. Office hours are super helpful. Would 100% recommend.",
    helpful: 142,
    wouldTakeAgain: true,
    difficulty: 4,
  },
  {
    id: "r2",
    professorId: "prof-1",
    author: "Sneha K.",
    year: "B.Tech 2nd Year",
    rating: 5,
    course: "Algorithm Design",
    date: "2024-10-02",
    text: "Amazing professor. Breaks down complex algorithms into digestible chunks. His analogies are unique and memorable. The exams are tough but completely fair if you attend his lectures.",
    helpful: 98,
    wouldTakeAgain: true,
    difficulty: 4,
  },
  {
    id: "r3",
    professorId: "prof-1",
    author: "Rahul T.",
    year: "M.Tech 1st Year",
    rating: 4,
    course: "Theory of Computation",
    date: "2024-09-18",
    text: "Very knowledgeable professor. Sometimes goes too fast for new students but genuinely tries to help. His research guidance is excellent. The course material is well-organized.",
    helpful: 67,
    wouldTakeAgain: true,
    difficulty: 3,
  },
  {
    id: "r4",
    professorId: "prof-2",
    author: "Priyanka N.",
    year: "B.Tech 3rd Year, ECE",
    rating: 5,
    course: "VLSI Design",
    date: "2024-12-01",
    text: "Prof. Sharma is incredible. She brings real industry experience to the classroom and makes VLSI feel exciting. Lab sessions are the best — she guides you hands-on.",
    helpful: 88,
    wouldTakeAgain: true,
    difficulty: 4,
  },
  {
    id: "r5",
    professorId: "prof-3",
    author: "Karan B.",
    year: "B.Tech 1st Year",
    rating: 5,
    course: "Real Analysis",
    date: "2024-11-22",
    text: "Dr. Singh is a mathematical genius who can actually teach. His proofs are beautiful and his intuitions are life-changing. This is why people apply to IIT Delhi.",
    helpful: 310,
    wouldTakeAgain: true,
    difficulty: 5,
  },
  {
    id: "r6",
    professorId: "prof-3",
    author: "Divya S.",
    year: "B.Tech 2nd Year",
    rating: 5,
    course: "Linear Algebra",
    date: "2024-10-14",
    text: "Best maths professor I have ever had. Period. He makes you fall in love with the subject. Difficult course but you will thank yourself later for taking it.",
    helpful: 225,
    wouldTakeAgain: true,
    difficulty: 5,
  },
];

// ─── Notifications ────────────────────────────────────────────────────────────
export const notifications = [
  {
    id: "n1",
    type: "review",
    title: "New review on Dr. Rajesh Kumar",
    desc: 'A student left a 5-star review for the course "Data Structures & Algorithms".',
    time: "2 minutes ago",
    read: false,
    icon: "⭐",
  },
  {
    id: "n2",
    type: "university",
    title: "IIT Delhi added 12 new professors",
    desc: "The Computer Science and Electrical Engineering departments have new faculty listings.",
    time: "1 hour ago",
    read: false,
    icon: "🏛️",
  },
  {
    id: "n3",
    type: "milestone",
    title: "RateYourProfessor hits 10,000 reviews!",
    desc: "Thank you to all students who contributed honest reviews. The community is growing!",
    time: "3 hours ago",
    read: false,
    icon: "🎉",
  },
  {
    id: "n4",
    type: "helpful",
    title: "Your review was marked helpful",
    desc: "47 students found your review of Prof. Priya Sharma helpful this week.",
    time: "1 day ago",
    read: true,
    icon: "👍",
  },
  {
    id: "n5",
    type: "trending",
    title: "Dr. Amit Singh is trending",
    desc: "Prof. Singh from IIT Delhi has received 23 new reviews in the last 7 days.",
    time: "2 days ago",
    read: true,
    icon: "🔥",
  },
  {
    id: "n6",
    type: "university",
    title: "VIT Vellore profile updated",
    desc: "New departments and 40+ faculty members have been added to the VIT Vellore listing.",
    time: "3 days ago",
    read: true,
    icon: "📋",
  },
  {
    id: "n7",
    type: "review",
    title: "New review on Prof. Priya Sharma",
    desc: 'A 4-star review was added for the course "Digital Electronics" at NSUT.',
    time: "4 days ago",
    read: true,
    icon: "⭐",
  },
  {
    id: "n8",
    type: "system",
    title: "Platform update: New rating categories",
    desc: 'We\'ve added "Clarity", "Helpfulness" and "Fairness" as separate rating dimensions.',
    time: "1 week ago",
    read: true,
    icon: "⚙️",
  },
  {
    id: "n9",
    type: "milestone",
    title: "DTU reaches 200+ professors listed",
    desc: "Delhi Technological University now has 210 professors rated on our platform.",
    time: "1 week ago",
    read: true,
    icon: "🏆",
  },
  {
    id: "n10",
    type: "helpful",
    title: "Weekly digest: Top reviews",
    desc: "See which professors received the most positive feedback this week across all universities.",
    time: "2 weeks ago",
    read: true,
    icon: "📰",
  },
];

// ─── Team (About Page) ────────────────────────────────────────────────────────
export const team = [
  {
    name: "Vikram Arora",
    role: "Co-founder & CEO",
    avatar: "VA",
    avatarBg: "linear-gradient(135deg, #7c3aed, #3b82f6)",
    bio: "B.Tech CSE from DTU. Built RYP after struggling to choose professors in his first year.",
    social: { linkedin: "#", twitter: "#" },
  },
  {
    name: "Riya Kapoor",
    role: "Co-founder & CTO",
    avatar: "RK",
    avatarBg: "linear-gradient(135deg, #06b6d4, #8b5cf6)",
    bio: "Full-stack engineer. Previously at Razorpay. Passionate about edtech and open data.",
    social: { linkedin: "#", twitter: "#" },
  },
  {
    name: "Dhruv Mehta",
    role: "Head of Product",
    avatar: "DM",
    avatarBg: "linear-gradient(135deg, #10b981, #3b82f6)",
    bio: "Product designer with 5 years in consumer apps. Obsessed with student-first UX.",
    social: { linkedin: "#", twitter: "#" },
  },
  {
    name: "Tanvi Singh",
    role: "Community Lead",
    avatar: "TS",
    avatarBg: "linear-gradient(135deg, #f59e0b, #ef4444)",
    bio: "Grew student communities across 20+ universities. Believes peer knowledge is priceless.",
    social: { linkedin: "#", twitter: "#" },
  },
];

export const timelineEvents = [
  {
    year: "2022",
    title: "The Idea",
    desc: "Vikram, frustrated by biased professor feedback, sketches the first wireframe on the back of an exam sheet.",
  },
  {
    year: "Q1 2023",
    title: "Beta Launch",
    desc: "Private beta with 3 Delhi universities. 500 students sign up in the first week.",
  },
  {
    year: "Q3 2023",
    title: "Going Public",
    desc: "Public launch with 10 universities, 1,200 professors, and 5,000 reviews. Featured in YourStory and Inc42.",
  },
  {
    year: "Q1 2024",
    title: "10K Reviews",
    desc: "Platform crosses 10,000 verified student reviews. Trusted by students at 20+ institutions.",
  },
  {
    year: "2025",
    title: "Expanding Nationally",
    desc: "Onboarding universities from every Indian state and launching international professor listings.",
  },
];
